export const GET_TYPES_WORK = 'GET_TYPE_WORK';
export const CREATE_TYPE_WORK= 'CREATE_TYPE_WORK';
export const UPDATE_TYPE_WORK = 'UPDATE_TYPE_WORK';
export const DELETE_TYPE_WORK = 'DELETE_TYPE_WORK';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
