export const GET_TEAMS = 'GET_TEAMS';
export const UPDATE_SELECTED_MEMBERS = 'UPDATE_SELECTED_MEMBERS';
export const CLEAR_SELECTED_MEMBERS = 'CLEAR_SELECTED_MEMBERS';
export const GET_PLACES = 'GET_PLACES';
export const UPDATE_SELECTED_PLACES = 'UPDATE_SELECTED_PLACES';
export const CLEAR_SELECTED_PLACES = 'CLEAR_SELECTED_PLACES';
export const GET_GEO_LOCATIONS = 'GET_GEO_LOCATIONS';
