export const SUBSCRIBE_USER = 'SUBSCRIBE_USER';
export const CREATE_WORK = 'CREATE_WORK';
export const UPDATE_STATUS_WORK = 'UPDATE_STATUS_WORK';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_OFF_LOCATIONS = 'GET_OFF_LOCATIONS';
export const ENABLE = {
    ON: 'ON',
    OFF: 'OFF',
    UNKNOWN: 'UNKNOWN'
};