export const GET_WORKS = 'GET_WORKS';
export const UPDATE_WORK = 'UPDATE_WORK';
export const CHANGE_STATUS_WORK = 'CHANGE_STATUS_WORK';
export const INITIALIZED_WORK = 'INITIALIZED_WORK';
export const RESET_SELECTED_WORK = 'RESET_SELECTED_WORK';
export const GET_WORK_ACTIVITIES = 'GET_WORK_ACTIVITIES';
